### PR TITLE
Update ProtonVPN profiles

### PR DESCRIPTION
**Pull request by Forage**
Some minor default param changes
Lots of server/IP changes per country

Also:
- New countries: AT, BE, BG, BR, CL, CR, CY, EC, EG, GR, ID, IN, IT, JP, KH, KR, LT, MA, MK, MT, PE, PH, PK, PR, PT, SI, TH, TR, TW, UA, VN
- Filename changes for countries: CH, CZ, ES, FR, HK, HU, IS, MX, NL, PL, RO, SE, UK
- Removal of countries: NG, SG, US (no country-wide P2P profiles available)

## Breaking change

```txt
Filename changes for countries: CH, CZ, ES, FR, HK, HU, IS, MX, NL, PL, RO, SE, UK
Removal of countries: NG, SG, US (no country-wide P2P profiles available)
```

## Proposed change

```txt
Update ProtonVPN profiles
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New provider (thank you!)
- [X] Updated provider (thank you!)
- [ ] New feature (which adds functionality to a provider script/repo usage)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by robdejonge** [comment]
Pardon my ignorance, but what does "no countrywide P2P profiles available" ... ? On https://protonvpn.com/vpn-servers, Singapore is listed as having P2P support.

**Comment by Forage** [comment]
The list on that page must be outdated. When you connect to your account, the list of actual profile downloads does not offer a P2P one for Singapore: 
image

**Comment by robdejonge** [comment]
Does in my client?

image

**Comment by Forage** [comment]
There must be different lists provided to different platforms in that case. An issue for Proton to correct. I can not download profiles used in the app, only what is made available on the website.

Yes, there are individual servers allowing P2P, like for the US and other countries as well. But I only include country wide profiles, as downloading all individual servers manually is too labour-intensive. And only those that allow P2P, to play nice with the VPN provider.

**Comment by robdejonge** [comment]
Logging in on the website (which is where you made your screenshot), I also see the same servers available. Perhaps I get other options because mine is a paid-for account?

Anyway, thanks for the response.

**Comment by Forage** [comment]
I have a paid Unlimited account ;) You are talking about individual servers, not country-wide.

**Pull request merged**
