### PR TITLE
Add back Perfect Privacy Provider

### PR DESCRIPTION
**Pull request by pchristod**
Hi,
I'm creating this PR in hopes of adding back native Perfect Privacy support into the new Provider Repo. For full transparancy, please see https://github.com/haugene/docker-transmission-openvpn/pull/1662 and https://github.com/haugene/docker-transmission-openvpn/issues/1695 for discussions around the removal.
I updated the configuration files with the once provided script and included the fix to the update-port.sh script found in https://github.com/haugene/docker-transmission-openvpn/pull/1574

Please kindly reject if you do not want to include support but based on the last Comment in https://github.com/haugene/docker-transmission-openvpn/issues/1695 it read as if it was a possibility after the split.

### CODE REVIEW

**Comment by haugene** [comment]
Hey. I was not present when all this went down the last time and I just have to read up on the threads and make sure I've got this right and think about what we do here. There's a lot going on at many fronts these days and timing wise this can go many ways. I might be able to pick it up soon, but shit might hit the fan and we'd have to revisit this after Easter. Ping me (mention) if it takes too long.

**Comment by pchristod** [comment]
Hey,
thank you for your fast comment on this. I fully understand and it sounds very reasonable 👍 
I too wasn't around when the Provider initially got removed but learned of it a little bit later after a Container Update (the hard way).
Please take your time and let me know if you require anything else.
Until then, happy holidays.

**Comment by Silversurfer79** [comment]
Hi guys, 
Any update ont his request? 
Im also looking for a new VPN that supports P2P, port forwarding, stricked no logging and thats not part of the 5-Eyes Alliance. These seems like a good option. 
Please advise
Thanks

**Comment by pchristod** [comment]
@haugene Did you guys have the chance to look this topic over & talk about it? Any update/response would be much appreciated :)
Thanks!

**Comment by varac** [comment]
@pchristod @Silversurfer79 @haugene  I created the PR that got Perfect Privacy removed, and the rationale was outlined in
https://github.com/haugene/docker-transmission-openvpn/pull/1662#issue-787726369:

> Perfect Privacy was founded and run by German/Austrian neo-Nazis,
> some of them convited to jail sentence for engaging in neo-nazi activities
> in Austria (https://en.wikipedia.org/wiki/Verbotsgesetz_1947).
> PP has denied to answer recent questions about this fact. Neither it has
> denied current relation to organised Nazi movements or the possibe continuation
> of the companies extreme right-wing consistence.
> Because of this it's removed by this commit.
> ...


I don't see any reason to revisit the decision to not support it at this time, since Perfect Privacy basically sits in silence regarding the numerous allegations I linked in the PR. Why would you ignore this and add it to this repo (putting technical arguments aside, I'm asking for your ethical point of view).

**Comment by pchristod** [comment]
Hi,

@varac Because I've outlined every piece of information and my point of view in the Issue I linked in my opening statement at length (including your original issue by the way) - which you seem to have either missed, skipped or ignored. I'm not going to repeat everything from the discussion there, if you want you are welcome to read up on it.

And to be frankly I do not appreciate the way you are trying to spin this by trying to personally shame us/me by implying we/I would for one ignore something (when even the owner of the repo and contributors responded friendly?) and also trying to ignite a discussion on ethical views. Why would you do this? I find this highly manipulative to be honest.

Most of us are simply customers and coincidentally we've been using this container where PP was a part of until the point of your Commit with the almost 10 year old links as sources from mostly 2012.

This might stem from the fact that Perfect Privacy also seems to be still widely viewed as a trustworthy and very secure Provider without logging (proven in the past ) in German speaking countries as per comparisons and discussions. I've never seen or heard the stuff you linked before from anyone and needed to read up on that stuff myself.

**Comment by haugene** [comment]
Alright. The time has come to have this conversation then. Sorry about the delay @pchristod, when I last commented back in March I did not expect it to take this long. Keywords: lots of work, long summer vacation and got a kid in the middle which has consumed exceptional amounts of time :laughing: 

First off. I do not wish for this project to have any political agenda. This is the first time that I've ever had to consider such ethical/political problems and I hope it's a while until next time :sweat_smile:  But let's all discuss this in a civil and orderly manner and see if we can't agree or at least respect and understand each others point of view. So here it goes...

Even if I said we don't have a political agenda, I'm all for being a decent human. Neo-Nazi stuff is just bad, no explanation needed. And yeah. If it was just a truth that PP was linked with that kind of ideology then sure - let's kick it out. *But...* I mean. You are innocent until proven otherwise, right? It's not PPs responsibility to prove to anyone that they don't worship Satan if someone would claim that.

The way I see it I have to agree with @pchristod. There's a bunch of articles pointing back to reporting in 2012 where, and no one is disputing this, some of the employees in PP stood trial for their links to right-wing groups. And I would expect a company to distance itself from these kinds of views.

But this is where I don't follow you anymore @varac. You say that:
> Perfect Privacy basically sits in silence regarding the numerous allegations

I just can't find that to be true. It's even in the links that you attached. Like in [thevpnshop](https://thevpnshop.com/reviews/perfect-privacy-vpn-review/) one. It start off by saying 
> Those Neo-Nazi members are no longer part of the organization

Then they throw in a dramatic "… at least, allegedly" without any justification other than that PP haven't talked much about it. That is not proof, that's just avoidance of a terrible topic for a company.

They also do get a response where the representative (a support agent) says that this is nonsense has nothing to do with their service, the people are long gone and they have taken a stand on this several times.

The journalists at thevpnshop asks if they shouldn't put up a notice on their webpage to avoid future questions. But I mean, come on. You can't have "We're not Nazis" on your home page. You try making your company do that.

And then there is the rebuttal in the 2015 article @pchristod links to. Google translate tells me that they answered among other things:
> All allegations at the time concerned the private affairs of the persons concerned and had nothing to do with Perfect Privacy itself

I can't see any justification to sit here in 2021 and say that this is more than an organization that had some bad apples back in 2012. I'm not sure where to draw the line. But this feels a bit like telling everyone driving a Volkswagen or Porsche that they should be ashamed of them selves. Because if you google them + Hitler stuff also shows up.

I mean, am I missing something here @varac? They have to be actively into it to be disqualified, or?
I'm still open to discuss this. And I'm all for banning Nazis. But this feels too thin to deny @pchristod to merge his VPN config files.

**Comment by pkishino** [comment]
I agree, I apologies for previously removing and closing down the discussion.
I fully agree that the points above are valid and this should be added again

**Comment by ilike2burnthing** [comment]
Wait wait wait! Let's not just jump past the most important part of this thread, "I got a kid." Did you steal a baby goat? 😋 Papa @haugene! Congrats! 🎉 

As to the much less fun topic, just to be clear (to anyone reading these topics for the first time) the convicted neo-nazis were founding members, not just random staff, and PP's responses over the years can be basically summarised as 'nuh uh' and 'shut up'. Also, I find it weird that even long after the event PP still only refer to 'allegations', despite everyone involved having been swiftly convicted.

Personally, any company that just brushes aside 'we used to be run by nazis' is not one I would put any trust in, certainly not give my money to. Putting out a decent statement at the time would have saved them a lot of mess, and making up for it now by not shutting down every interview question on the topic could at least put an end to it. No need for a **Now 100% not Nazis!** flashing gif on their homepage, just an acknowledgement and explanation of what happened, that all of 100 people will likely ever actually read in full.

While obviously innocent before proven guilty is a great standard in courts, we aren't a jury, and PP definitely don't seem like they're going to share any evidence. So I think a more appropriate standard would be akin to solving the mystery of where all the cookies went, but when you ask the child with crumbs on their top they just scream and run away. Can I prove they ate the cookies? No. Is their refusal answer anything about it still a pretty big giveaway? Yea...

As for how that impacts this project - users can still add PP as a custom provider, so all that changed for them was in the setup. The only message which came across from PP being removed was that while there exists justified doubt, contributors/maintainers here wouldn't put effort into including it.

**Comment by haugene** [comment]
> Wait wait wait! Let's not just jump past the most important part of this thread, "I got a kid." Did you steal a baby goat?  Papa @haugene! Congrats!

Thank you very much :smile: :baby: Life v2.0 starting now. Although it feels more rocky, like an alpha or 2.0-rc1 or something :laughing: We'll get there!

As for your the topic at hand. I can't say I disagree with you at any particular point, except maybe the conclusion. PP should have been more forthcoming, there are many ways to distance themselves on their website other than investing in heavy GIFs and we're not a jury and can allow ourselves to draw some conclusions without stone hard proof as well.

And yes. They were founding members. That makes a difference, I agree. Is that what turns this from a yes to a no though :man_shrugging:

The discussions were concluded fast the last time. I'll leave this open for now so people can say their peace.
As for the users they can use it as a custom provider. But also, now that we've split the repos they can just set `GITHUB_CONFIG_SOURCE_REPO=pchristod/vpn-configs-contrib` when running the container and it will load the configs from @pchristod's fork. So this will not be very tough anyways, it's very much about principle as I see it. Not many practical implications.

**Comment by ilike2burnthing** [comment]
Oh you're only at technical preview stages, you've got 18yrs before RTM 😋

I definitely agree it's more principle than practical - no money is changing hands, it's not exactly promotion of a company to be included with ~50 others in a GitHub repo, and it's far from bashing the fash. The 'inconvenience' to PP users is next to none, so if a stance was taken it would at least not be 'punishing' anyone.

As for future requests, I suppose they could be directed here with the comment that short of some ground breaking public statement from PP, nothing will change.

**Comment by pchristod** [comment]
Hi,

@haugene thanks for jumping in and first of all congratulations on your recent life changes, even if we do not know each other personally :smile:

I would like to thank you for your first statement, the Volkswagen comparison is honestly a good one even though much older of course. I think this was the point I'm trying to make and I'm glad it was understood correctly even with a hard subject like this at hand.

I'm still curious about what ground breaking statements you would expect @ilike2burnthing? To me your messages here and the other discussion seem you are stuck anyways on the same opinion no matter what happens. And let's not forget this is a 10 year old topic, I wouldn't expect anything to come up at this point, especially when these accused members left a long time ago and nothing else came up past that point, apart from the original articles? In comparison it comes down to the great Volkswagen example again...

Everything else I would say was already summarized by @haugene, probably better than I would have done it anyways. 

I would still be happy to see PP make a full return here and it seems at least a few others would also. Unless what @haugene wrote in his latest message here (about the split and setting the sources) is already the decision on the whole subject. This part got me a bit confused to be honest.

**Comment by ilike2burnthing** [comment]
If we're going to use VW as an example, then while they don't have 'not nazis' on their homepage, they do have an entire section dedicated to their wartime dealings, which includes their use of slave labour from concentration camps - https://www.volkswagenag.com/en/group/history/chronicle/1937_1945.html

This is gone into in even more detail in their 188 page document on the issue, as well as the the various investigations, commemorations, and funds established by VW - https://www.volkswagenag.com/presence/konzern/documents/history/englisch/Katalog_Erinnerungsst%C3%A4tte_EN.pdf

That seems a hell of a lot better than a PP-style response of, "It was a long time ago, the 'allegations' were just about a few people who are no longer with the company, we don't want to talk about it anymore, go away."

PP obviously don't need to set up a $19m fund, but acknowledgement and explanation would go a long way, and should have been done nearly a decade ago. The reason I describe such a thing as 'ground breaking' is because at this point it is just never going to happen.

**Comment by pchristod** [comment]
So basically your point is even though we do not know the full story behind it apart from a few links here and there posted by somome, that a 'Sorry' is missing in some form, which might not even be sincere or the truth? Same as countless other companies practice it each year while being accused of mistreading employees, funding the wrong organizations, supporting the wrong politicians or just being caught doing other evil shit.

What exactly does that help and matter anyways? I would understand your reasoning completely if they had just continued in the same exact way for the last 10 years plus swept everything under the rug if proven guilty.

Seeing as the problem got erradicated from the roots by making structural changes within the company (fully intended or by coincidence) a long time ago it makes this a hundred times better for me and my moral conscience than any 'Sorry we fucked up' PR Stunt like other companies issue while continuing doing evil shit around the clock 24/7, where no one sweats a tear afterwards.

What I'm trying to say: I rather have it knowingly solved then not taken care of at all.

**Comment by varac** [comment]
> >     Perfect Privacy basically sits in silence regarding the numerous allegations
> 
> I just can't find that to be true. It's even in the links that you attached. Like in thevpnshop one. It start off by saying
> 
> >     Those Neo-Nazi members are no longer part of the organization
> 
> Then they throw in a dramatic "… at least, allegedly" without any justification other than that PP haven't talked much about it. That is not proof, that's just avoidance of a terrible topic for a company.
> 
> They also do get a response where the representative (a support agent) says that this is nonsense has nothing to do with their service, the people are long gone and they have taken a stand on this several times.
> 
> The journalists at thevpnshop asks if they shouldn't put up a notice on their webpage to avoid future questions. But I mean, come on. You can't have "We're not Nazis" on your home page. You try making your company do that.

But in what way does the company even try to do that ?

There is still no official statement of PP about this. The quotes above are from a anonymous support agent saying they are not part of PP anymore (see `An Ugly Response to an Ugly History` in https://thevpnshop.com/reviews/perfect-privacy-vpn-review/). It's irrelevant what some "support agent" says in a non-public conversation. As long as we don't get on official statement from PP we must assume nothing has changed. Even if the members on trial left, who else from their potential like-minded crew might still be there ? 

I completely agree with @ilike2burnthing comment:

> As for future requests, I suppose they could be directed here with the comment that short of some ground breaking public statement from PP, nothing will change.

 
> And then there is the rebuttal in the 2015 article @pchristod links to. Google translate tells me that they answered among other things:
> 
>     All allegations at the time concerned the private affairs of the persons concerned and had nothing to do with Perfect Privacy itself

One sentence about PP even says (translated):

> Perfect Privacy never had a right wing background was always politically neutral.

I think the answers of PP disqualify by that sentence alltogether, given founding members ended up in trial for neo-nazi activities. How should I believe any other word in this interview after that ?


> I can't see any justification to sit here in 2021 and say that this is more than an organization that had some bad apples back in 2012. I'm not sure where to draw the line. But this feels a bit like telling everyone driving a Volkswagen or Porsche that they should be ashamed of them selves. Because if you google them + Hitler stuff also shows up.

A few founding memebers of PP were Nazis and went to court for that. So we're not talking about a few bad apples here but rather  a quite rotten stem, sticking to analogies.

I have no intention to shame or blame any PP user here, this was never the point. I believe that the vast majority of PP users doesn't even know about this controvercy. 
The point is rather that this project has the moral responsibility to not let uninformed users put more money into the wrong hands, and we *do* need to draw a line, and imho PP is where it starts.

**Comment by ilike2burnthing** [comment]
> So basically your point is [...] that a 'Sorry' is missing in some form, which might not even be sincere or the truth?

Eh, no - "acknowledgement and explanation" - e.g. not referring to the convictions of their founding members as 'allegations', explaining what actually happened, what was known when and by who, how their activities either went unnoticed or unchallenged within the company, what they've done to redress the damage done and prevent it from happening again. In other words, all the basic things any company should do when there's an internal fuck up, rather than those copy and paste 'sorry' statements which I agree are a meaningless PR exercise in an attempt to run out the clock on the public attention span.

As for the changes in the company, it was 2 new people and 1 person (who had been around for years) given more work. Seeing as they were replacing the arrested neo-Nazis, I hardly see this as a good action by PP, rather a necessary one to continue functioning. I have no idea about the number of staff PP employs, so 2/3 people may be nothing in the larger scheme of the company. Also, tongue firmly in cheek here but, we know nothing about those 2/3 people (not that I expect to), for all we know their last names could be Himmler, Goebbels, and Goering. Basically what I'm trying to say through that sarcasm is that a few new staff does not resolve an issue like this.

To be clear though, I have no idea if PP are all secret Nazis, I very much doubt it, but that isn't my cause for concern. Rather, they screwed up from the top, and they've done nothing to address it, actually being pretty crappy when press asks - that's worrisome. Honestly, if they had just said at the time that were all shocked by it, they would be looking internally, and then 6mths later come out with a report or even just a statement with the main points (and it wasn't just a whitewash obviously), this wouldn't be an issue now.

**Comment by pchristod** [comment]
@varac You mention moral responsibilities and informing users that they are putting money into wrong hands by drawing a line. 

You came to this conclusion to save every current PP user today (almost 10 years later) simply by assuming you can read out the lies and stamp it as completely evil. 

Again, why should I care as a user of the company PP today having heard/read nothing bad of that sort in almost a decade apart from this discussion - rather the opposite.

I'm going to assume this is fine now based on the information I gathered, otherwise I trust shit would've probably hit the fan already as it always does in the internet because PP is still very much in focus in German speaking countries, and it never forgets.

@ilike2burnthing You are basically talking about the ideal world scenario here. While that is wishful we probably all know this is not how it works mostly, unless the pressure becomes to unbearable. The rest is just guessing work as no one knows the internal structure but them - more so a decade later. We can only assume based on what information come to light outside.

All in all still the main point being made I see is a missing explanation. Honestly it's quite interesting that you say this exact same situation wouldn't be an issue if you had something official to read at hand which probably wouldn't make any more real changes then there are already.

**Comment by ilike2burnthing** [comment]
Not being evasive is a bare minimum, I'd hardly call that an ideal world scenario.

I did clarify that if they had released something it would only be of worth if, "it wasn't just a whitewash obviously." From the very start the objection has been to the fact that they haven't answered any basic questions, so yes if they had answered those basic questions then there wouldn't be an objection (again, assuming the answers were actually substantive).

**Comment by pchristod** [comment]
While I would if I recall countless other affairs from various companies in the past or present and seeing how they where handled in the majority. Evasive and downplaying until it doesn't work anymore is just the standard approach. Doesn't matter much anyways who's right here - I think we both agree that it's not good and it should be different, just isn't in most real world examples.

And I didn't say you did any different in my last message. Still comes down to you wanting only some sort of official (substantive) work up on the subject which is all I wrote. 

Recounting that I'm at the point asking myself why we are still discussing this, there is no full length explanation, report or FAQ Nazi Page as far as we could see yet and there won't be any in the future - as again this is a decade old. So it comes back to what @haugene already summarized as everything further on from my, your or anyone else's side is simply guessing, personal opinion, reading into or wishful thinking. No point on spinning this around any further going in circles again and again.

**Comment by ilike2burnthing** [comment]
> not referring to the convictions of their founding members as 'allegations', explaining what actually happened, what was known when and by who, how their activities either went unnoticed or unchallenged within the company, **what they've done to redress the damage done and prevent it from happening again**.

If you want to know what I think would have made a practical difference, then see the part in bold, but all of that is fairly important.

Before this becomes a trend of me having to quote what I've already said, let me quote you instead, "[...] you seem to have either missed, skipped or ignored [it]. I'm not going to repeat everything [...]" - https://github.com/haugene/vpn-configs-contrib/pull/2#issuecomment-912992430

PP was founded and ran by neo-Nazis, and company resources seem to have been used to some degree to host and protect at least a Nazi forum, yet supposedly no one else knew - seems like BS but ok. They could have explained how it happened, got rid of any other Nazis, and put measures in place to stop something similar in future - they could even have put a cherry on top and donated a percentage of the earnings from that period to a relevant charity.

In almost a decade they've either done none of that, or for some odd reason done it all in secret but then get their backs up if someone dares ask about it, and continue to refer to the criminal convictions of their former colleagues as 'allegations'. Given how unlikely the latter seems, I side heavily on it being the former. As such, I would personally never use them, and I support their removal from this project. Users can still add them as a custom provider, like many users do for other VPNs. Better yet, they could read this and decide to switch to a different VPN.

**Comment by pchristod** [comment]
Hi,

I'll try to keep this short as I don't see any sense in sending the same re-phrased messages back and forth constantly. Same as you probably.
No point in continuing that imho because it's getting nowhere as we can see.

I think I've said everything I had to say at this point. I disagree completely with your personal opinion on the matter and obviously I support the re-adding of PP (hence the PR). I'll also keep using the Service as I'm satisfied by the functionality and still have yet to see any new information other than two personal opinions as to why it is currently worse than any other VPN Provider in 2021.

There's no bad blood here, you are entitled to your opinion on the matter and I respect it. So I wish you a good day :+1:

**Comment by pchristod** [comment]
Closing PR as I don't expect anything to happen here further after 6 months & huge discussion. If at some point necessary in the future it can either be reopened or a new PR can be created.

**Comment by midnightmercenary** [comment]
How do I add Perfect Privacy as a custom provider?

**Comment by pchristod** [comment]
> How do I add Perfect Privacy as a custom provider?

If this is still relevant, then you can either store the config files locally and use the 'Custom' option, fork the support repo yourself and add the configs as per instruction, or use the repo I'm using where config is added already.

**Comment by pchristod** [comment]
> How do I add Perfect Privacy as a custom provider?

If this is still relevant, then you can either store the config files locally and use the 'Custom' option, fork the support repo yourself and add the configs as per instruction, or use a forked repo where PP config is added already.

**Pull request closed without merging**
