### PR TITLE
Update fr.ovpn tls-cipher=DEFAULT:@SECLEVEL=0

### PR DESCRIPTION
**Pull request by crepeas**
corrects certificate error until keepsolidInc push update

VPNUNLIMITED RESPONSE : 
"First of all, we'd like to apologize for the inconvenience you had with the service.

We confirm that we are aware of the issue.

In fact, our technical department has already generated new certificates, but in order to implement them, we need to update all our servers. This process has already been planned and is expected to take place in the near future. We have no ETA for now.

In the meantime,

As a temporary workaround, you can add this line to your OVPN file:

tls-cipher=DEFAULT:@SECLEVEL=0

This way you can turn off errors in the logs and this will help establish a VPN connection.

You can find more information on the OpenVPN forum in this regard:

https://forums.openvpn.net/viewtopic.php?t=23979"

## Breaking change

```txt
<placeholder>
```

## Proposed change

```txt
<placeholder>
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New provider (thank you!)
- [x] Updated provider (thank you!)
- [ ] New feature (which adds functionality to a provider script/repo usage)
- [x] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by pkishino** [comment]
I’ll try to rework this today and apply it to all configs for the provider

**Comment by Yondz** [comment]
Hi folks,

I started to get weird issues today in my container logs, and my transmission is now down : 

```
No bundled config script found for VPNUNLIMITED. Defaulting to external config
Will get configs from https://github.com/haugene/vpn-configs-contrib.git
Repository is already cloned, checking for update
Already up to date.
Already on 'main'
Your branch is up to date with 'origin/main'.
Found configs for VPNUNLIMITED in /config/vpn-configs-contrib/openvpn/vpnunlimited, will replace current content in /etc/openvpn/vpnunlimited
Starting OpenVPN using config ca-tr.ovpn
Modifying /etc/openvpn/vpnunlimited/ca-tr.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/vpnunlimited/ca-tr.ovpn:111: tls-cipher=DEFAULT:@SECLEVEL=0 (2.5.5)

Use --help for more information.
```

I guess this comes from this PR, is this working on you side ? 

I've been using VPNUNLIMITED provider for quite a while, using the equivalent `tls-cipher` options by passing it via `OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --tls-cipher DEFAULT:@SECLEVEL=0` but somehow having it like that in the .ovpn file seems to be broken when using `haugene/transmission-openvpn:latest` :(

**Comment by SensehacK** [comment]
> I've been using VPNUNLIMITED provider for quite a while, using the equivalent `tls-cipher` options by passing it via `OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --tls-cipher DEFAULT:@SECLEVEL=0` but somehow having it like that in the .ovpn file seems to be broken when using `haugene/transmission-openvpn:latest` :(


Similar story as well
```bash
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/vpnunlimited/ca-tr.ovpn:111: tls-cipher=DEFAULT:@SECLEVEL=0 (2.5.5)
Use --help for more information.
```

My docker config
```docker
      environment:
            - OPENVPN_OPTS=--tls-cipher DEFAULT:@SECLEVEL=0
```


I was keeping my docker `transmission-openvpn` alive due to previous OpenSSL certificate error 
> OpenSSL: Cannot Load inline Certificate file https://github.com/haugene/vpn-configs-contrib/issues/162

**Comment by crepeas** [comment]
Hi, the format is wrong, 

My file had this setup and was working : 

client
dev tun
reneg-sec 0
persist-tun
persist-key
ping 5
ping-exit 30
nobind
comp-lzo no
remote-random
remote-cert-tls server
auth-user-pass /config/openvpn-credentials.txt
auth-nocache
route-metric 1
cipher AES-256-CBC
auth sha512
**tls-cipher "DEFAULT:@SECLEVEL=0"**

You actually need the " in the config file, it must have disapeared in the copy and paste.

**Review by crepeas — COMMENTED** [review]
tls-cipher "DEFAULT:@SECLEVEL=0"

format was wrong from keepsolid, the one listed here is working.

**Comment by Yondz** [comment]
I've opened a PR following your indications @crepeas : https://github.com/haugene/vpn-configs-contrib/pull/249

Thanks :)

**Pull request merged**
