### PR TITLE
Fastestvpn openvpn updates

### PR DESCRIPTION
**Pull request by bijfy**
## Breaking change

```txt
<placeholder>
```

## Proposed change

```txt
<placeholder>
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New provider (thank you!)
- [ ] Updated provider (thank you!)
- [ ] New feature (which adds functionality to a provider script/repo usage)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by pkishino** [comment]
can you please review those conflicts and fix, thank you

**Comment by bijfy** [comment]
Hi. Can you check now ?

**Comment by pkishino** [comment]
still showing the following:
Conflicting files
openvpn/fastestvpn/Australia1-UDP.ovpn
openvpn/fastestvpn/Germany-UDP.ovpn
openvpn/fastestvpn/India1-UDP.ovpn

**Comment by bijfy** [comment]
I have deleted them now. Should I do another

**Comment by bijfy** [comment]
Can you try now ?

**Pull request closed without merging**
