### PR TITLE
latest protonvpn country configs only

### PR DESCRIPTION
**Pull request by cacula**
## Breaking change

```txt
- Removed all ProtonVPN specific Servers - only Country Settings left ( Server will be randomly choosed )
- XX.protonvpn.com.XX.ovpn are now XX.protonvpn.net.XX.ovpn
```

## Proposed change

```txt
- reduce config files to 2 files per country only - tcp and udp
- update all configs to latest version 10112022
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New provider (thank you!)
- [x] Updated provider (thank you!)
- [ ] New feature (which adds functionality to a provider script/repo usage)
- [x] Breaking change (fix/feature causing existing functionality to break)

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by Forage** [comment]
Why remove them?

**Comment by Forage** [comment]
Fixed with #158 and took it one step further.

**Comment by cacula** [comment]
@Forage thanks for fixing - was my first commit. left out server specific profiles to minimize complexity and because i don't see the usecase for them.

**Comment by Forage** [comment]
@cacula I recommend that you change your connection user name on the Proton VPN site now that yours has been exposed.

**Comment by lmpynix** [comment]
> Why remove the server specific profiles to begin with?
Is there an answer to this question?  I can't be the only one whose setup this breaks (especially after #158).

**Comment by outadoc** [comment]
@cacula All free servers were removed, which broke my setup and I can't connect to anything anymore. Was this intended? If not, could it be reverted?

**Comment by Forage** [comment]
@outadoc good point. There isn't a single country-wide profile available for free account. At the same time, there isn't a single free server specific profile that officially supports P2P either. That leaves you with providing your own selected profile externally as the only option.

**Comment by mark-monteiro** [comment]
For those who now have a broken setup, I wrote a short guide on how to migrate to using a custom config file here: https://github.com/haugene/vpn-configs-contrib/issues/159#issuecomment-1320758800

**Pull request merged**
