### PR TITLE
fastestvpn config files

### LINKED ISSUE #33: FASTESTVPN NEW CONFIG FILES
## Before creating this request I have:

**REQUIRED**
- [X] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
<FASTESTVPN>
```

### Where are the configs?

**REQUIRED**
```txt
<[Fastestvpn_ovpn(2).zip](https://github.com/haugene/vpn-configs-contrib/files/7040894/Fastestvpn_ovpn.2.zip)>
```
### Additional context

*Optional*

``` <[Fastestvpn_ovpn(2).zip](https://github.com/haugene/vpn-configs-contrib/files/7040894/Fastestvpn_ovpn.2.zip) for optional> ```

### PR DESCRIPTION
**Pull request by bijfy**
## Breaking change

```txt
<placeholder>
```

## Proposed change

[Fastestvpn_ovpn.zip](https://github.com/haugene/vpn-configs-contrib/files/7042728/Fastestvpn_ovpn.zip)

```


## Type of change
<!--
  What type of change does your PR introduce?
  NOTE: Please, check only 1! box!
  If your PR requires multiple boxes to be checked, you'll most likely need to
  split it into multiple PRs. This makes things easier and faster to code review.
-->

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New provider (thank you!)
- [X] Updated provider (thank you!)
- [ ] New feature (which adds functionality to a provider script/repo usage)
- [ ] Breaking change (fix/feature causing existing functionality to break)


## Additional information
<!--
  Details are important, and help maintainers processing your PR.
  Please be sure to fill out additional details, if applicable.
-->

- This PR fixes or closes issue: ```fixes #33 ```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist
<!--
  Put an `x` in the boxes that apply. You can also fill these out after
  creating the PR. If you're unsure about any of them, don't hesitate to ask.
  We're here to help! This is simply a reminder of what we are going to look
  for before merging your code.
-->

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

<!-- Please check *Preview* before submitting -->

### CODE REVIEW

**Review by pkishino — CHANGES_REQUESTED** [review]
Hello, please see the other PRs regarding how to update the configs.
we need the actual updated ovpn files here
thanks

**Comment by bijfy** [comment]
> Hello, please see the other PRs regarding how to update the configs.
> we need the actual updated ovpn files here
> thanks

Hi, I have deleted vpn files link and uploaded it with zipped ovpn files . Is it good or have to do something else? Thanks

**Comment by pkishino** [comment]
yeah, no, sorry. remove the zip file, extract the files and REPLACE the outdated ovpn files in the fastestvpn folder in the repo. Please see e.g. #22

**Comment by bijfy** [comment]
Thanks for your help. I give up . Please delete my pull request.

**Comment by pkishino** [comment]
there, please see the changes I made..

**Review by pkishino — APPROVED** [review]

**Comment by bijfy** [comment]
Thanks.

**Pull request merged**
