### PR TITLE
New Windscribe certs valid after 20 July 2021 at 17:00 UTC

### LINKED ISSUE #19: Windscribe is sunsetting current certificates on 20 July 2021
## Before creating this request I have:

**REQUIRED**
- [X] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
Windscribe
```

### Where are the configs?

**REQUIRED**
```txt
No download that I know of; they use a config generator, for which I believe there may be an existing scraper (see below).
```
### Additional context

*Optional*

```
Windscribe just gave notice that they are sunsetting their current certificates on 20th July, so the existing OVPN files will need to be updated. As far as I can tell there is no way to just download all of the OVPN files from them at once, but a scraper was mentioned by @wilmardo in [this PR](https://github.com/haugene/docker-transmission-openvpn/pull/1691). Hopefully that can be used to grab the new files.

From Windscribe: "We are sunsetting our OpenVPN certificate authority and beginning to phase out compression on July 20 2021 at 17:00 UTC. If you're using an OpenVPN version less than 2.4 you will need download new configurations and install them on July 20 2021 after 17:00 UTC as they no longer contain compression options and it is not possible to gracefully transition without doing this at the same time we perform maintenance."

Links:
[https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222](https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222)
[https://windscribe.com/getconfig/openvpn](https://windscribe.com/getconfig/openvpn)
```

### PR DESCRIPTION
**Pull request by wilmardo**
## Breaking change

```txt
These certificates will only be valid after 20 July 2021 at 17:00 UTC.
See https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222 for details.
```
## Proposed change

```txt
Contains new certificates valid after 20 July 2021 at 17:00 UTC.
OVPN files were scraped using wilmardo/windsribe-ovpn-config-scraper
and updated to point to config file for login credentials.
```
Superseeds #20 (includes @brossow his commits but squashed retaining the author for his contributor badge). I updated the scraper with new locations, the difference can be seen in my commit. I also updated the README table, I ran the tests twice and this was the result both times.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New provider (thank you!)
- [x] Updated provider (thank you!)
- [ ] New feature (which adds functionality to a provider script/repo usage)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #19```
- Changes have NOT been tested because they're only valid after the date/time specified, at least for OpenVPN versions prior to 2.4.

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated

### CODE REVIEW

**Comment by wilmardo** [comment]
https://github.com/haugene/docker-transmission-openvpn/pull/1873

Does it make sense to merge this here or should I also open a PR on the main repo?

**Comment by pkishino** [comment]
I’ll merge it in here, but best to wait until 20th, right?

**Comment by tim0901** [comment]
[According to the Windscribe blog](https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222) it should be ok to update to the new certs now:

> **OpenVPN 2.4 or newer outside of our apps:** You will need to download a new configuration from our website and configure it on any devices that use the current configurations before July 20th 2021 17:00 UTC. You can do this right now.

**Comment by tim0901** [comment]
The old certificates have now been depreciated, so this can be merged.

**Pull request merged**
