### PR TITLE
Config from Russia

### PR DESCRIPTION
**Pull request by FaridunBurakov**
https://antizapret.prostovpn.org/antizapret-tcp.ovpn

## Breaking change

```txt
<placeholder>
```

## Proposed change

```txt
<placeholder>
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New provider (thank you!)
- [ ] Updated provider (thank you!)
- [ ] New feature (which adds functionality to a provider script/repo usage)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by pkishino** [comment]
Please merge the two PRs first of all, urs related to the same provider so no need for two.
Second,I had a brief look. How does this authenticate? No username/password?
Private keys?
Also, can you edit the documentation to add the provider and any special settings that are needed?
Thank you

**Comment by FaridunBurakov** [comment]
Hey!
I am new to GitHub? sorry (. 
Yes, you are right. There is no login and password verification.
the service works on redirecting DNS requests different from the provider in Russia. Viewing online movies and torrent sites is not blocked.
This proxy is part of the Anti-Ban of Russia. Only blocked sites from the unified register of the Russian Federation are proxied. 
You can also visit the site yourself for more understanding.
https://antizapret.prostovpn.org/

**Comment by pkishino** [comment]
you created two separete pull requests, why? please edit this one and add the commit from the other one. No need for two..
But looking at this I don't think it will work without adding some extra documentation etc as all our profiles expect a username/password combination..
@haugene let me know what you think please

**Comment by haugene** [comment]
Is this still relevant @FaridunBurakov? And you have tested it and it works? What you're saying is that it's open for some sort of anonymous access? I would also expect there to have to be some sort of username/password combination - right? And then the `auth-user-pass` option needs to be present for this container to work as @pkishino says.

**Comment by pkishino** [comment]
Feel free to open if still wanted

**Pull request closed without merging**
