### PR TITLE
New PR Mullvad including cities

### PR DESCRIPTION
**Pull request by C9Glax**
## Breaking change

```txt
Last PR didn't include cities which broke Portforwarding
```

## Proposed change

```txt
Also downloaded all current city-configs in addition to the "all" configs
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New provider (thank you!)
- [x] Updated provider (thank you!)
- [ ] New feature (which adds functionality to a provider script/repo usage)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Review by mostlydev — COMMENTED** [review]
Looks fine to me.  Thanks for all that work.

**Comment by pkishino** [comment]
Please resolve then I’ll merge

**Review by mostlydev — APPROVED** [review]

**Comment by mostlydev** [comment]
I cannot resolve it.  I don't have write access.

**Comment by mostlydev** [comment]
@C9Glax will have to do that.  This is above my paygrade.

**Comment by C9Glax** [comment]
Nope sorry me neither
grafik

**Comment by pkishino** [comment]
Rebase locally then push a new commit

**Pull request closed without merging**
